[php]
extensions = ["pdo_mysql", "gd", "zip"]
version = "8.1"

[phases.setup]
nixPkgs = ["php81", "php81Extensions.pdo_mysql", "php81Extensions.gd", "php81Extensions.zip", "nginx"]

[phases.install]
cmds = [
  # Создание всех необходимых директорий одной командой
  "mkdir -p /etc/php-fpm.d /var/log/nginx /var/lib/nginx /etc/nginx /run/php-fpm /tmp/php-sessions /var/www/html",

  # Генерация всех конфигурационных файлов одним блоком
  "cat > /etc/php-fpm.conf << 'EOF'
[global]
pid = /run/php-fpm/php-fpm.pid
error_log = /var/log/php-fpm.log
log_level = notice
include=/etc/php-fpm.d/*.conf
EOF",

  "cat > /etc/php-fpm.d/www.conf << 'EOF'
[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.backlog = 65535
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 10
pm.max_requests = 500
chdir = /
catch_workers_output = yes
php_flag[display_errors] = off
php_admin_value[error_log] = /var/log/php-fpm-www.log
php_admin_flag[log_errors] = on
EOF",

  # Генерация fastcgi_params
  "cat > /etc/nginx/fastcgi_params << 'EOF'
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;
fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;
fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;
fastcgi_param  REDIRECT_STATUS    200;
EOF",

  # Генерация mime.types
  "cat > /etc/nginx/mime.types << 'EOF'
types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                 js;
    application/atom+xml                  atom;
    application/rss+xml                   rss;
    text/mathml                           mml;
    text/plain                            txt;
    text/vnd.sun.j2me.app-descriptor      jad;
    text/vnd.wap.wml                      wml;
    text/x-component                      htc;
    image/png                             png;
    image/tiff                             tif tiff;
    image/vnd.wap.wbmp                    wbmp;
    image/x-icon                           ico;
    image/x-jng                            jng;
    image/x-ms-bmp                         bmp;
    image/svg+xml                           svg svgz;
    image/webp                             webp;
    application/font-woff                  woff;
    application/font-woff2                 woff2;
    application/java-archive               jar war ear;
    application/json                       json;
    application/mac-binhex40               hqx;
    application/msword                      doc;
    application/pdf                         pdf;
    application/postscript                  ps eps ai;
    application/rtf                         rtf;
    application/vnd.apple.mpegurl           m3u8;
    application/vnd.google-earth.kml+xml    kml;
    application/vnd.google-earth.kmz        kmz;
    application/vnd.ms-excel                xls;
    application/vnd.ms-fontobject           eot;
    application/vnd.ms-powerpoint           ppt;
    application/vnd.oasis.opendocument.graphics     odg;
    application/vnd.oasis.opendocument.presentation  odp;
    application/vnd.oasis.opendocument.spreadsheet  ods;
    application/vnd.oasis.opendocument.text         odt;
    application/vnd.wap.wmlc                 wmlc;
    application/x-7z-compressed              7z;
    application/x-cocoa                       cco;
    application/x-java-archive-diff           jardiff;
    application/x-java-jnlp-file              jnlp;
    application/x-makeself                    run;
    application/x-perl                        pl pm;
    application/x-pilot                        prc pdb;
    application/x-rar-compressed               rar;
    application/x-redhat-package-manager       rpm;
    application/x-sea                           sea;
    application/x-shockwave-flash               swf;
    application/x-stuffit                       sit;
    application/x-tcl                           tcl tk;
    application/x-x509-ca-cert                   der pem crt;
    application/x-xpinstall                       xpi;
    application/xhtml+xml                         xhtml;
    application/xspf+xml                          xspf;
    application/zip                               zip;
    application/octet-stream                      bin exe dll;
    application/octet-stream                      deb;
    application/octet-stream                      dmg;
    application/octet-stream                      iso img;
    application/octet-stream                      msi msp msm;
    application/vnd.oasis.opendocument.chart      odc;
    application/vnd.oasis.opendocument.database   odb;
    application/vnd.oasis.opendocument.formula    odf;
    application/vnd.oasis.opendocument.graphics-template   otg;
    application/vnd.oasis.opendocument.image               oti;
    application/vnd.oasis.opendocument.presentation-template   otp;
    application/vnd.oasis.opendocument.spreadsheet-template    ots;
    application/vnd.oasis.opendocument.text-master            odm;
    application/vnd.oasis.opendocument.text-template          ott;
    application/vnd.oasis.opendocument.text-web               oth;
    application/x-7z-compressed                 7z;
    application/x-abiword                        abw;
    application/x-bzip                            bz2;
    application/x-cbr                             cbr;
    application/x-cdr                             cdr;
    application/x-cram-queue                      cram;
    application/x-director                        dir;
    application/x-dvi                             dvi;
    application/x-font-bdf                        bdf;
    application/x-font-pcf                        pcf;
    application/x-font-snf                        snf;
    application/x-freemind                        mm;
    application/x-gnumeric                        gnumeric;
    application/x-graphite                        gra;
    application/x-gtar                             gtar;
    application/x-hdf                              hdf;
    application/x-ica                              ica;
    application/x-info                              info;
    application/x-install-instructions              install;
    application/x-iso9660-image                     iso;
    application/x-java-jnlp-file                    jnlp;
    application/x-latex                              latex;
    application/x-lzh-compressed                      lzh;
    application/x-mie                                 mie;
    application/x-mobipocket-ebook                     mobi;
    application/x-ms-application                       application;
    application/x-ms-shortcut                          lnk;
    application/x-ms-wmd                                wmd;
    application/x-ms-wmz                                wmz;
    application/x-ms-xbap                               xbap;
    application/x-msaccess                              mdb;
    application/x-msbinder                              obd;
    application/x-mscardfile                            crd;
    application/x-msclip                                clp;
    application/x-msdownload                            exe;
    application/x-msmediaview                            m13;
    application/x-msmetafile                             wmf;
    application/x-msmoney                                mny;
    application/x-mspublisher                            pub;
    application/x-msschedule                             scd;
    application/x-msterminal                             trm;
    application/x-mswrite                                wri;
    application/x-netcdf                                 nc;
    application/x-nzb                                    nzb;
    application/x-pkcs12                                 p12;
    application/x-pkcs7-certificates                     p7b;
    application/x-pkcs7-certreqresp                       p7r;
    application/x-pkcs7-crl                               crl;
    application/x-pkcs7-mime                              p7m;
    application/x-pkcs7-signature                         p7s;
    application/x-planperfect                             wpd;
    application/x-pocket-word                             psw;
    application/x-rar                                     rar;
    application/x-reject                                  rjt;
    application/x-sdp                                     sdp;
    application/x-silverlight-app                         xap;
    application/x-stuffitx                                sitx;
    application/x-subrip                                  srt;
    application/x-tar                                     tar;
    application/x-tex                                     tex;
    application/x-tex-tfm                                 tfm;
    application/x-texinfo                                 texi;
    application/x-tgif                                    obj;
    application/x-ustar                                   ustar;
    application/x-wais-source                             src;
    application/x-x509-ca-cert                            der;
    application/x-xfig                                    fig;
    application/x-xliff                                   xlf;
    application/x-xpinstall                               xpi;
    application/x-xz                                      xz;
    application/x-zmachine                                z1;
    application/xaml+xml                                  xaml;
    application/xcap-diff+xml                             xdf;
    application/xenc+xml                                  xenc;
    application/xhtml+xml                                 xhtml;
    application/xml                                       xml;
    application/xml-dtd                                   dtd;
    application/xop+xml                                   xop;
    application/xproc+xml                                 xpl;
    application/xslt+xml                                  xslt;
    application/xspf+xml                                  xspf;
    application/xv+xml                                    mxml;
    application/yang                                      yang;
    application/yin+xml                                   yin;
    application/zip                                       zip;
    audio/adpcm                                           adp;
    audio/basic                                            au;
    audio/midi                                             mid;
    audio/mp4                                              m4a;
    audio/mpeg                                             mp3;
    audio/ogg                                              oga;
    audio/x-aiff                                           aif;
    audio/x-mpegurl                                        m3u;
    audio/x-ms-wax                                         wax;
    audio/x-ms-wma                                         wma;
    audio/x-pn-realaudio                                   ram;
    audio/x-wav                                            wav;
    image/bmp                                              bmp;
    image/cgm                                              cgm;
    image/g3fax                                            g3;
    image/gif                                              gif;
    image/ief                                              ief;
    image/jpeg                                             jpeg;
    image/ktx                                              ktx;
    image/png                                              png;
    image/prs.btif                                         btif;
    image/sgi                                              sgi;
    image/svg+xml                                          svg;
    image/tiff                                             tiff;
    image/vnd.adobe.photoshop                              psd;
    image/vnd.djvu                                         djvu;
    image/vnd.dwg                                          dwg;
    image/vnd.dxf                                          dxf;
    image/vnd.fastbidsheet                                 fbs;
    image/vnd.fpx                                          fpx;
    image/vnd.fst                                          fst;
    image/vnd.fujixerox.edmics-mmr                         mmr;
    image/vnd.fujixerox.edmics-rlc                         rlc;
    image/vnd.ms-modi                                      mdi;
    image/vnd.net-fpx                                      npx;
    image/vnd.wap.wbmp                                     wbmp;
    image/vnd.xiff                                         xif;
    image/webp                                             webp;
    image/x-3ds                                            3ds;
    image/x-cmu-raster                                     ras;
    image/x-cmx                                            cmx;
    image/x-freehand                                       fh;
    image/x-icon                                           ico;
    image/x-mrsid-image                                    sid;
    image/x-pcx                                            pcx;
    image/x-pict                                           pic;
    image/x-portable-anymap                                pnm;
    image/x-portable-bitmap                                pbm;
    image/x-portable-graymap                               pgm;
    image/x-portable-pixmap                                ppm;
    image/x-psd                                            psd;
    image/x-rgb                                            rgb;
    image/x-tga                                            tga;
    image/x-xbitmap                                        xbm;
    image/x-xpixmap                                        xpm;
    image/x-xwindowdump                                    xwd;
}
EOF",

  # Права доступа
  "chown -R www-data:www-data /run/php-fpm /var/log/nginx || true",
  "chmod -R 755 /run/php-fpm || true"
]
